version: '3.2'
services:
  redis:
    image: bitnami/redis:6.0.1
    container_name: redis
    environment:
      - REDIS_PASSWORD=WbeSOSvsvhonorzT512gy6Nc7qi9Twah
    ports:
      - 6379:6379

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DATABASE=0
      - REDIS_ZSET=autocomplete
      - REDIS_PASS=WbeSOSvsvhonorzT512gy6Nc7qi9Twah
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
